[package]
name = "Damians_Custom_DateTime_Parser"
version = "0.1.0"
edition = "2021"
licence = "MIT"
descriprion = "Custom library for date and time parsing using pest."

[dependencies]
anyhow = "1.0.93"
pest = "2.7.14"
pest_derive = "2.7.14"

